### ISSUE TITLE
SetAsync ignoring DefaultSlidingExpiration set in MySqlCacheOptions 

### ISSUE THREAD

**Issue by DustinReagan** [PomeloFoundation/Caching-MySQL#45]
using Pomelo.Extensions.Caching.MySql version 2.1.3

DI:
```
services.AddDistributedMySqlCache(opts =>
            {
                opts.ConnectionString = config.GetConnectionString("DistributedCache");
                opts.SchemaName = "DistributedCache";
                opts.TableName = "ApiCache";
                opts.DefaultSlidingExpiration = TimeSpan.FromMinutes(10);
            });
```

Usage:

```
_cache.Set(  "my_key", Encoding.UTF8.GetBytes("my_value") );
```

Error:
```
System.InvalidOperationException: Either absolute or sliding expiration needs to be provided.
   at Pomelo.Extensions.Caching.MySql.DatabaseOperations.ValidateOptions(Nullable`1 slidingExpiration, Nullable`1 absoluteExpiration)
   at Pomelo.Extensions.Caching.MySql.DatabaseOperations.SetCacheItem(String key, Byte[] value, DistributedCacheEntryOptions options)
   at Pomelo.Extensions.Caching.MySql.MySqlCache.Set(String key, Byte[] value, DistributedCacheEntryOptions options)
   at Microsoft.Extensions.Caching.Distributed.DistributedCacheExtensions.Set(IDistributedCache cache, String key, Byte[] value)
   ```
   
   
   Expectation:  If `DistributedCacheEntryOptions.SlidingExpiration` is not specified, the `Set` should use the `DefaultSlidingExpiration` as set in the `AddDistributedMySqlCache` options.

**Comment by DustinReagan** [comment]
https://github.com/PomeloFoundation/Caching-MySQL/pull/46

**Comment by ChaosEngine** [comment]
Fixed by https://www.nuget.org/packages/Pomelo.Extensions.Caching.MySql/2.1.4 and https://github.com/PomeloFoundation/Caching-MySQL/releases/tag/v2.1.4
